services:
  dev-database:
    image: postgres:16
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ContactsDb
    ports:
      - "5432:5432"
        
  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
